---
title: "r_data_types"
author: "Charles Hendrickson"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create a vector called vec_1

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)

# What is the class of the vector?
class(vec_1)

# What type of variable does it store?
typeof(vec_1)

# Access the 3rd element and store as
vec_1[3]

vec_1_e3 <- vec_1[3]

# Access the 1st element and store as
vec_1[1]

vec_1_e1 <- vec_1[1]

# Access the 5th through 7th elements and store as
vec_1[5:7]
vec_1_e5to7 <- vec_1[5:7]

# Reassign vec_1 as a character using as.character, stored as vec_1_char. What does the output look like?

vec_1_char <- as.character(vec_1)

vec_1_char
# Output looks like numbers with quotes around them.

```


# Create a vector called vec_2. 
vec_2 should contained named elements, where town = "Santa Barbara, location = "Rincon", swell = "south"

```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")

class(vec_2)

typeof(vec_2)

vec_2[2]

vec_2["location"]

# What is the class of vector elements? 

class(vec_2)

# What is the length of vec_2?
length(vec_2)


# Access the 2nd element by name and store as vec_2_e2
vec_2["location"]

vec_2_e2 <- vec_2["location"]

```

# Write code to create a data frame called df_1 that looks like this:

```{r}
df_1 <- data.frame(region = c("A", "B", "A", "D"),
                   species = c("otter", "great_white", "sea_lion", "grey_whale")
                   )
```














